# ==========================================
# APPLICATION
# ==========================================

spring.application.name=resource-booking-system

server.port=8080


# ==========================================
# POSTGRESQL DATABASE
# ==========================================

spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/resource_booking_db}
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:Amruta@123}
spring.datasource.driver-class-name=org.postgresql.Driver


# ==========================================
# SEED USER CREDENTIALS (updated strong pwd)
# ==========================================

seed.admin.password=${SEED_ADMIN_PASSWORD:Spiderman@2026}
seed.user.password=${SEED_USER_PASSWORD:Spiderman1@2026}




# Defaults to 'update' in development. In production environments, set JPA_DDL_AUTO=validate.
# Database schema creation script is provided in schema.sql.
spring.jpa.hibernate.ddl-auto=${JPA_DDL_AUTO:update}
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.open-in-view=false




jwt.secret=${JWT_SECRET:MyVeryLongSecretKeyForResourceBookingSystemJWT2026SecureKey}
jwt.expiration=86400000



springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html